### ISSUE TITLE
Official submission to matbench?

### ISSUE THREAD

**Issue by ardunn** [ihalage/Finder#3]
Hi there,

[Matbench](https://matbench.materialsproject.org) maintainer here. I read through a bit of your paper https://onlinelibrary.wiley.com/doi/10.1002/advs.202200164 and I think the website would benefit greatly from having Finder on the leaderboard? Is there any chance you have the data somewhere in the repo, or if you could make an official submission to `matbench` with the python package?

**Comment by ihalage** [comment]
Hi @ardunn,

I have created a pull request but it appears to be failing. When recording matbench results, I had to run several tasks in parallel and save the json file for each task separately due to time constraints rather than waiting for the whole program to run sequentially and create a single `results.json.gz` file. But I did combine these results to a single `results.json.gz` with "utf-8" encoding, and this seems to be the reason why the pull request is failing. Could you give me directions on how to compress the results.json file so that it's compatible? Or do you have an alternative?

**Comment by ardunn** [comment]
Hi @ihalage sure, let me look into it on the matbench repo https://github.com/materialsproject/matbench/pull/174

**Comment by ihalage** [comment]
PR has been merged. Closing the issue.
